name: Run 9hits Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-action@v2

    - name: Run Docker container
      run: |
        docker run -d --network=host --name=9hits 9hitste/app /nh.sh --token=882530ba3f2d8d77451cdc028cd700c8 --system-session --ex-proxy-sessions=10 --allow-crypto=no --session-note=9hits-pool --note=my-laptop --hide-browser
